## Experiment with the getSpei package
## https://seschaub.github.io/getspeiweb/pages/getSpei_main.html

## Install
#devtools::install_github('seschaub/getSpei')

require(getSpei)

setwd("~/Desktop/University of Utah PhD /Research/data/spei/")

## Data Processing (Global)

#d2 <- all_spei(spei_files = "spei12", start_y = 2010, end_y = 2021)


## Data Processing (Local)
location_id = c("Karachi", "Lahore", "Peshawar", "Quetta")
longitude = c(67.0011, 74.3587, 71.5249, 66.9750)
latitude = c(24.8607, 31.5204, 34.0151, 30.1798)
locations_df = data.frame(location_id, longitude, latitude)

# specify arguments and run function:
d1 <- spec_spei(spei_files = "spei12", start_y = 2010, end_y = 2021, 
                locations = locations_df)



## Visualization

# run function
#list1 <- all_spei_viz(c("spei12"), year = 2010, month = 8) 

# visualizing
#grid1 <- list1$grid  # extract grid from list generated by all_spei_viz 
#d2    <- list1$data  # extract SPEI data from list generated by all_spei_viz 
#cutoffs <- c(-2, -1.5, -1, 1, 1.5, 2) # decide of cutoffs
#color <- c("#ca0020","#f4a582","#a1d99b","#92c5de","#0571b0") # define colors
#map1 <- levelplot(d2 ~ lon * lat, data = grid1, at = cutoffs, cuts = 6, pretty = T, 
                  #col.regions = color) # create map

#show(map1)



